require("core.mappings")
require("core.plugins")
require("core.configs")

require("plugins.lsp")
require("plugins.mason")
require("plugins.cmp")
require("plugins.treesitter")
require("plugins.neo-tree")
require("plugins.telescope")
require("plugins.null-ls")
require("plugins.autopairs")
require("plugins.buffline")
require("plugins.comments")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.symbols-outline")
require("plugins.toggleterm")
require("plugins.which-key")
require("plugins.ufo")

require("plugins.themes.bluloco")
require("plugins.themes.eldritch")
require("plugins.themes.monokai-pro")
require("plugins.themes.neosolarized")
require("plugins.themes.witch")

require("core.colors")
